name: CI

# Определите, когда workflow должен запускаться
on:
  push:
    branches: [main] # Запускать на пушах в ветку main
  pull_request:
    branches: [main] # Запускать на pull request в ветку main

# Определите задания, которые будут выполняться
jobs:
  test:
    runs-on: ubuntu-latest # Укажите на какой машине будет выполняться workflow

    services:
      xvfb: # Сервис для запуска тестов в среде с доступом к X Server
        image: selenium/standalone-chrome
        options: --shm-size=512m
        ports:
          - 4444:4444

    steps:
      - name: Checkout code
        uses: actions/checkout@v4 # Загружает ваш код из репозитория

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20" # Укажите версию Node.js

      - name: Cache node_modules
        uses: actions/cache@v4
        with:
          path: node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Install dependencies
        run: npm install # Установка зависимостей

      - name: Install Puppeteer
        run: npm install puppeteer

      - name: Run tests
        run: |
          export DISPLAY=:99.0
          npm test
